name: Build example

on:
    push:
        branches:
            - main

jobs:
    setup-node:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v3

            - name: setting up the npm framework
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'

            - name: installing dependencies
              run: npm install

            - name: zipping all the nodes and app files
              run: |
                npm install zip
                zip -r build.zip

            
            - name: listing
              run: ls -alhR
