name: Checkout example

on:
  workflow_dispatch

jobs:
    checkout_example:
      runs-on: ubuntu-latest

      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: show listing and contents directories
          run: ls -alhR

